views/administration.py
from flask import Blueprint, render_template, flash, request, redirect, url_for
from flask_login import current_user

from database.database import get_db
from helpers.auth import is_admin_logged

bp = Blueprint('administration', __name__, url_prefix='/administration')

@bp.get('/users')
def load_admin_page():
    db = get_db()
    uzivatele_role = []
    try:
        uzivatele_role = db.execute("SELECT id_uzivatele,username, nazev FROM uzivatele NATURAL JOIN role_uzivatelu "
                                    "NATURAL JOIN role").fetchall()
    except db.Error as e:
        flash('Nelze načíst data z databáze.', 'error')
    return render_template('/administration.html', users_roles = uzivatele_role, is_admin_logged=is_admin_logged(),
                           is_authenticated=current_user.is_authenticated)

@bp.get('/delete')
def delete_user():
    user_id = request.args.get('id')
    db = get_db()
    try:
        db.execute("DELETE FROM role_uzivatelu WHERE id_uzivatele = ?", (user_id, ))
        db.execute("DELETE FROM uzivatele WHERE id_uzivatele = ?", (user_id, ))
        db.commit()
        flash('Uživatel byl smazán.', 'success')
    except db.Error as e:
        flash('Chyba při mazání.', 'error')
        print(e)
    return redirect(url_for('administration.load_admin_page'))

@bp.get('/grant')
def grant_permissions():
    user_id = request.args.get('id')
    db = get_db()
    try:
        db.execute("UPDATE role_uzivatelu SET id_role = (SELECT id_role FROM role WHERE nazev = 'administrator') "
                   "WHERE id_uzivatele = ?", (user_id, ))
        db.commit()
        flash('Uživateli byla přidělena práva administrátora.', 'success')
    except db.Error as e:
        flash('Chyba při práci s db.', 'error')
        print(e)
    return redirect(url_for('administration.load_admin_page'))

views/auth.py
from flask import Blueprint, request, render_template, flash, redirect, url_for
from flask_login import LoginManager, login_user, current_user, logout_user

from database.database import get_db
from helpers.User import User
from helpers.auth import password_hash, is_admin_logged

bp = Blueprint('auth', __name__, url_prefix='/auth')

login_manager = LoginManager()

@login_manager.user_loader
def load_user(id_uzivatele):
    db = get_db()
    try:
        user_data = db.execute(
            "SELECT * FROM uzivatele WHERE id_uzivatele = ?",
            (id_uzivatele, )
        ).fetchone()
        if user_data is None:
            return None
        else:
            return User(user_data['id_uzivatele'], user_data['username'])
    except db.Error as e:
        flash('Omlouváme se, nastal problém s databází.', 'error')
        print('DB Error: ' + str(e))
        return None


@bp.get('/login')
def login_form():
    after_registration = request.args.get('after_registration')
    return render_template('auth/login.html', data={}, after_registration=after_registration,
                           is_authenticated=current_user.is_authenticated, is_admin_logged=is_admin_logged())

@bp.post('/login')
def login_action():
    db = get_db()
    data = request.form
    try:
        user_data = db.execute(
            "SELECT * FROM uzivatele WHERE username = ? AND password = ?",
            (data['username'], password_hash(data['password'])) #password_hash(data['password'])
        ).fetchone()
        if user_data is None:
            flash('Zadali jste nesprávné přihlašovací údaje.', 'error')
            return render_template('auth/login.html', data=data)

        user = User(user_data['id_uzivatele'], user_data['username'])
        login_user(user)
        return redirect(url_for('intro', after_login = True))
    except db.Error as e:
        flash('Omlouváme se, nastal problém s databází.', 'error')
        print('DB Error: ' + str(e))
        return render_template('auth/login.html', data=data, is_admin_logged=is_admin_logged(),
                               is_authenticated=current_user.is_authenticated)

@bp.get('/logout')
def logout_action():
    logout_user()
    return redirect(url_for('intro', after_logout = True, is_admin_logged=is_admin_logged(),
                            is_authenticated=current_user.is_authenticated))

@bp.get('/registration')
def registration():
    return render_template('auth/registration.html', data={})

@bp.post('/registration')
def register():
    db = get_db()
    data = request.form
    db.execute(
        "INSERT INTO uzivatele (username, password) VALUES (?, ?)",
        (data['username'], password_hash(data['password']))
    ).lastrowid  # přidá další id v řadě
    user_id = db.execute(
        "SELECT id_uzivatele FROM uzivatele WHERE username = ? and password = ?",
        (data['username'], password_hash(data['password']))
    ).fetchone()
    db.execute(
        "INSERT INTO role_uzivatelu(id_uzivatele, id_role) VALUES(?, 0)",
        (user_id)
    )
    db.commit()
    return redirect(url_for('auth.login_form', after_registration=True, is_authenticated=current_user.is_authenticated,
                            is_admin_logged=is_admin_logged()))

views/categories.py
from flask import Blueprint, request, flash, redirect, url_for, render_template
from flask_login import current_user

from database.database import get_db
from helpers.auth import is_admin_logged

bp = Blueprint('categories', __name__, url_prefix='/category')

@bp.get('/delete')
def delete_category():
    category_id = request.args.get('id')
    db = get_db()
    try:
        db.execute(
            "DELETE FROM kategorie WHERE id_kategorie = ?",
            (category_id)
        )
        db.commit()
        flash('Záznam byl úspěšně smazán.', 'alert success')
    except db.Error as e:
        flash('Není možno smazat záznam.', 'error')
        print(e)
    return redirect(url_for('intro'))

@bp.get('/category')
def show_category():
    category_id = request.args.get('id')
    produkty = []
    info = None
    db = get_db()
    try:
        produkty = db.execute(
            "SELECT id_produktu, produkty.nazev, vyrobce FROM produkty JOIN kategorie USING(id_kategorie) "
            "WHERE id_kategorie = ?",
            (category_id, )
        ).fetchall()
        category_info = db.execute(
            "SELECT nazev, popis, barva FROM kategorie WHERE id_kategorie = ?",
            (category_id, )
        ).fetchone()
    except db.Error as e:
        flash('Není možno načíst databázi.', 'error')
        print(e)
    return render_template('categories/categories.html', category_id=category_id, products = produkty,
                           category_info=category_info, is_admin_logged=is_admin_logged(),
                           is_authenticated=current_user.is_authenticated)

@bp.get('/newcategory')
def new_category():
    return render_template('categories/newcategory.html', data = {}, is_admin_logged=is_admin_logged(),
                           is_authenticated=current_user.is_authenticated)

@bp.post('/newcategory')
def add_category():
    db = get_db()
    data = request.form
    if (data['popis'] == ''): # pokud je bez popisu
        db.execute(
            "INSERT INTO kategorie (nazev, popis, barva) VALUES (?, ?, ?)",
            (data['nazev'], '', data['barva'])
        ).lastrowid  # přidá další id v řadě
    else: # s popisem
        db.execute(
            "INSERT INTO kategorie (nazev, popis, barva) VALUES (?, ?, ?)",
            (data['nazev'], data['popis'], data['barva'])
        ).lastrowid  # přidá další id v řadě
    db.commit()
    return redirect(url_for('intro', is_authenticated=current_user.is_authenticated, is_admin_logged=is_admin_logged()))

views/items.py
from flask import Blueprint, render_template
from flask_login import current_user

from helpers.auth import is_admin_logged

bp = Blueprint('items', __name__, url_prefix='/items')

@bp.get('/new_item')
def load_new_item_page():
    return render_template('/new_item.html', is_admin_logged=is_admin_logged(),
                           is_authenticated=current_user.is_authenticated)

views/products.py
from flask import Blueprint, request, flash, redirect, url_for, render_template
from flask_login import current_user

from database.database import get_db
from helpers.auth import is_admin_logged

bp = Blueprint('products', __name__, url_prefix='/products')

@bp.get('/delete_product')
def delete_product():
    product_id = request.args.get('id')
    kategorie = 0
    db = get_db()
    try:
        kategorie = db.execute("SELECT id_kategorie FROM produkty WHERE id_produktu = ?", (product_id, ) ).fetchone()[0]
        db.execute(
            "DELETE FROM produkty WHERE id_produktu = ?",
            (product_id, )
        )
        db.commit()
        flash('Záznam byl úspěšně smazán.', 'alert success')
    except db.Error as e:
        flash('Není možno smazat záznam.', 'error')
        print(e)
    return redirect(url_for('categories.show_category', id=kategorie))

@bp.get('/product')
def show_prices():
    product_id = request.args.get('id')
    ceny = []
    product_info = None
    db = get_db()
    try:
        ceny1 = db.execute(
            "SELECT id_produktu, strftime('%Y-%m-%d', datetime(datum)) datum, cena, zdroj FROM ceny WHERE "
            "id_produktu = ? AND id_uzivatele IS NULL ", # záznamy přidané nepřihlášenými uživateli
            (product_id, )
        ).fetchall()
        ceny2 = db.execute(
            "SELECT id_produktu, strftime('%Y-%m-%d', datetime(datum)) datum, cena, username, zdroj FROM ceny "
            "JOIN uzivatele USING(id_uzivatele) WHERE id_produktu = ? "
            "AND id_uzivatele IS NOT NULL", # záznamy přidané administrátory
            (product_id, )
        ).fetchall()
        ceny = ceny1 + ceny2
        product_info = db.execute(
            "SELECT nazev, vyrobce FROM produkty WHERE id_produktu = ?",
            (product_id, )
        ).fetchone()
        category_info = db.execute(
            "SELECT barva FROM kategorie JOIN produkty USING(id_kategorie) WHERE id_produktu = ?",
            (product_id, )
        ).fetchone()
    except db.Error as e:
        flash('Není možno načíst databázi.', 'error')
        print(e)
    return render_template('products/products.html', prices = ceny, category_info=category_info,
                           product_info=product_info, is_admin_logged=is_admin_logged(),
                           is_authenticated=current_user.is_authenticated)

@bp.get('/delete_price')
def delete_price():
    product_id = request.args.get('id')
    date = request.args.get('date')
    db = get_db()
    try:
        db.execute(
            "DELETE FROM ceny WHERE id_produktu = ? AND datum = ?",
            (product_id, date)
        )
        db.commit()
        flash('Záznam byl úspěšně smazán.', 'alert success')
    except db.Error as e:
        flash('Není možno smazat záznam.', 'error')
        print(e)
    return redirect(url_for('products.show_prices', id=product_id))

@bp.get('/newproduct')
def new_product():
    categories = []
    db = get_db()
    categories = db.execute(
        "SELECT id_kategorie, nazev FROM kategorie"
    ).fetchall()
    return render_template('products/newproduct.html', data = {}, categories=categories,
                           is_admin_logged=is_admin_logged(), is_authenticated=current_user.is_authenticated)

@bp.post('/newproduct')
def add_product():
    db = get_db()
    data = request.form
    category_id = int(data['kategorie'][0])
    try:
        db.execute(
            "INSERT INTO produkty (nazev, vyrobce, id_kategorie) VALUES (?, ?, ?)",
            (data['nazev'], data['vyrobce'], category_id, )
        ).lastrowid  # přidá další id v řadě
        db.commit()
        flash('Záznam byl úspěšně vložen.', 'alert success')
    except db.Error as e:
        flash('Není možno přidat záznam - pravděpodobně jste zadali špatný název kategorie.', 'error')
        print(e)
    return redirect(url_for('categories.show_category', id=category_id, is_authenticated=current_user.is_authenticated,
                            is_admin_logged=is_admin_logged()))

@bp.get('/newpriceadm')
def new_price_admin():
    products = []
    db = get_db()
    products = db.execute(
        "SELECT id_produktu, nazev FROM produkty"
    ).fetchall()
    return render_template('products/newprice_admin.html', data = {}, products=products,
                           is_admin_logged=is_admin_logged(), is_authenticated=current_user.is_authenticated)

@bp.get('/newprice')
def new_price_anonymous():
    products = []
    db = get_db()
    products = db.execute(
        "SELECT id_produktu, nazev FROM produkty"
    ).fetchall()
    return render_template('products/newprice_anonymous.html', data = {}, products=products,
                           is_admin_logged=is_admin_logged(), is_authenticated=current_user.is_authenticated)

@bp.post('/newpriceadm')
def add_price_admin():
    db = get_db()
    data = request.form
    product_id = data['produkt']
    try:
        user_id = current_user.get_id()
        db.execute(
            "INSERT INTO ceny (datum, id_produktu, cena, zdroj, id_uzivatele) VALUES (DATE(?), ?, ?, ?, ?)",
            (str(data['datum']), product_id, data['castka'], data['zdroj'], user_id)
        ).lastrowid  # přidá další id v řadě
        db.commit()
        flash('Záznam byl úspěšně vložen.', 'alert success')
    except db.Error as e:
        flash('Není možno přidat záznam - pravděpodobně jste zadali špatný název produktu.', 'error')
        print(e)
    return redirect(url_for('products.show_prices', id=product_id, is_authenticated=current_user.is_authenticated,
                            is_admin_logged=is_admin_logged()))


@bp.post('/newprice')
def add_price_anonymous():
    db = get_db()
    data = request.form
    product_id = data['produkt']
    try:
        db.execute(
            "INSERT INTO ceny (datum, id_produktu, cena, zdroj) VALUES (?, ?, ?, ?)",
            (str(data['datum']), product_id, data['castka'], data['zdroj'])
        ).lastrowid  # přidá další id v řadě
        db.commit()
        flash('Záznam byl úspěšně vložen.', 'alert success')
    except db.Error as e:
        flash('Není možno přidat záznam - pravděpodobně jste zadali špatný název produktu.', 'error')
        print(e)
    return redirect(url_for('products.show_prices', id=product_id, is_authenticated=current_user.is_authenticated,
                            is_admin_logged=is_admin_logged()))

templates/administration.html
{% extends "base.html" %}


{% block title %} Administrace {% endblock %}

{% block content %}
    <h2>Administrace</h2>
    {% if is_admin_logged %}
        <p>Seznam uživatelů:</p>
        <table class="items-table">
            <thead>
                <tr>
                    <th>Uživatel</th>
                    <th>Role</th>
                    <th>Udělit oprávnění</th>
                    <th>Smazat</th>
                </tr>
            </thead>
            <tbody>
                {% for user in users_roles %}
                    <tr>
                        <td>{{user.username}}</td>
                        <td>{{user.nazev}}</td>
                        <td><a href="{{url_for('administration.grant_permissions', id=user.id_uzivatele)}}"><span class="material-icons">done_outline</span></a></td>
                        <td><a href="{{url_for('administration.delete_user', id=user.id_uzivatele)}}"><span class="material-icons">delete</span></a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <div class="alert danger">
            Zde nemáte co dělat, přihlašte se.
        </div>
    {% endif %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="cs">
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">

    <title>Katalog piv - {% block title %}{% endblock %}</title>

    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <style>{% block style %}{% endblock %}</style>
</head>
<body>

    <nav>
        <div id="titulek">
            <span class="material-icons">sports_bar</span>  Katalog piv
        </div>
        <div id="menu">
            <a href="/">Domů</a>
            <a href="{{url_for('items.load_new_item_page')}}">Přidat záznam</a>
            {% if is_admin_logged %}
                <a href="{{url_for('administration.load_admin_page')}}">Administrace</a>
            {% endif %}
            {% if is_authenticated %}
                <a href="{{url_for('auth.logout_action')}}">Odhlásit</a>
            {% else %}
                <a href="{{url_for('auth.login_form')}}">Přihlášení</a>
            {% endif %}
        </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages | length > 0 %}
            <div class="messages">
                {% for category, message in get_flashed_messages(with_categories=true) %}
                    <div class="message {{ category }}">{{ message }}</div>
                {% endfor %}
            </div>
        {% endif %}
    {% endwith %}

    <main>
        {% block content %}
        {% endblock %}
    </main>

    <footer>
        <div>
        <h3>Kontakt:</h3>
            <address>
                Michal Koudela<br>
                xkoudela@mendelu.cz<br>
                Tel. 123 456 789
            </address>
        </div>
        <div>
            <h3>Kde nás najdete:</h3>
            <iframe src="https://frame.mapy.cz/s/pazelozole" width="400" height="280"></iframe>
        </div>
    </footer>

</body>
</html>

templates/intro.html
{% extends "base.html" %}

{% block title %} Úvod {% endblock %}

{% block content %}
    {% if after_login %}
        <div class="alert success">
            Přihlášení bylo úspěšné.
        </div>
    {% else %}
        {% if after_logout %}
            <div class="alert success">
                Odhlášení bylo úspěšné.
            </div>
            {% else %}
                <h2>Vítejte na webu s katalogem pivních produktů!</h2>
            {% endif %}
    {% endif %}

    <p>Začněte výběrem kategorie:</p>
<!--
    <table class="items-table">
        <thead>
            <tr>
                <th>Název</th>
                <th>Popis</th>
                <th>Zobrazit produkty</th>
                {% if is_admin_logged %}
                    <th>Smazat</th>
                {% endif %}
            </tr>
        </thead>
        <tbody>
            {% for category in categories %}
            <tr>
                <td>{{category.nazev}}</td>
                <td>{{category.popis}}</td>
                <td><a href="{{url_for('categories.show_category', id=category.id_kategorie)}}"><span class="material-icons">list_alt</span></a></td>
                {% if is_admin_logged %}
                    <td><a href="{{url_for('categories.delete_category', id=category.id_kategorie)}}"><span class="material-icons">delete</span></a></td>
                {% endif %}
            </tr>
        {% endfor %}
        </tbody>
    </table>-->
    {% for three_categories in categories | batch(3, '&nbsp;') %} <!-- rozdělí list kategorií na trojice -->
        <div class="vedlesebe">
            {% for category in three_categories %}
                {% if category.id_kategorie != NULL %}
                    <a href="{{url_for('categories.show_category', id=category.id_kategorie)}}"><div class="newitem-items" style="background: {{category.barva}}">{{category.nazev}}</div></a>
                {% endif %}
            {% endfor %}
        </div>
    {% endfor %}
{% endblock %}

templates/new_item.html
{% extends "base.html" %}

{% block title %} Přidání nové položky {% endblock %}

{% block content %}
    {% if is_admin_logged %}
        <h2>Přidání nové položky</h2>
        <p>Zvolte si, co chcete přidat:</p>
        <div class="vedlesebe">

                <a href="{{url_for('products.new_product')}}"><div class="newitem-items">Přidat nový produkt</div></a>
                <a href="{{url_for('categories.new_category')}}"><div class="newitem-items">Přidat novou kategorii</div></a>
                <a href="{{url_for('products.new_price_admin')}}"><div class="newitem-items">Přidat novou cenu</div></a>

        </div>
    {% endif %}


    {% if not is_admin_logged %}
        {% if is_authenticated %}
            <div class="alert danger">
                Jste přihlášen jako běžný uživatel bez oprávnění, nemůžete tedy přidávat nové kategorie ani produkty a mazat záznamy. Pro udělení těchto práv kontaktujte administrátora.
            </div>
            <h2>Přidání nové položky</h2>
            <p>Zvolte si, co chcete přidat:</p>
            <a href="{{url_for('products.new_price_admin')}}"><div class="newitem-items">Přidat novou cenu</div></a>
        {% else %}
            <h2>Přidání nové položky</h2>
            <p>Zvolte si, co chcete přidat:</p>
            <a href="{{url_for('products.new_price_anonymous')}}" style="text-decoration: none"><div class="newitem-items">Přidat novou cenu</div></a>
            <br>
            Pro více možností se <a href="{{url_for('auth.login_form')}}">přihlašte</a> nebo <a href="{{url_for('auth.registration')}}">zaregistrujte</a>.
        {% endif %}
    {% endif %}


{% endblock %}